### PR TITLE
Added database connection and login + register functionalities

### PR DESCRIPTION
**Pull request by andrei2308**
I added connection to a mongodb database, defined a user model and scheme, and added the connection string in the .env file. I added register and login functionalities, where register saves a user in the database with username, password and email, using bcrypt to hash the password and save it as a hash in the database and login takes the user and password from the body, searches the user in the database, hash the password using the same hashing algortihm and compare the two hashes ( zero proof knowledge ). I also added a json web token ,that is valid for an hour after the user is logged in successful, that uses  a JWT_SECRET added in the .env file.

### CODE REVIEW

**Comment by meteabduraman** [comment]
@andrei2308 does this address #6?

**Comment by meteabduraman** [comment]
@andrei2308  `node_modules` should never be committed, can you remove them and add back the `.gitignore` file while making sure it contains `node_modules`?

`node_modules` contains the code of the entirety of your dependencies, but anyone can install them if they run `npm install` in your project, if you have a `package.json` and a `package-lock.json` in which the versions are declared

**Comment by andrei2308** [comment]
> @andrei2308 does this address #6?

It addresses #6 and #7

**Comment by andrei2308** [comment]
> @andrei2308 `node_modules` should never be committed, can you remove them and add back the `.gitignore` file while making sure it contains `node_modules`?
> 
> `node_modules` contains the code of the entirety of your dependencies, but anyone can install them if they run `npm install` in your project, if you have a `package.json` and a `package-lock.json` in which the versions are declared

I understand, it's done.

**Pull request merged**
